DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS ACCOUNTS;

CREATE TABLE ACCOUNTS (
    A_NUM       INTEGER     PRIMARY KEY,
    A_NAME      VARCHAR(50) NOT NULL,
    A_EMAIL     VARCHAR(50) NOT NULL,
    A_PHONE     VARCHAR(10) NOT NULL,
    A_ADDRESS   VARCHAR(60) NOT NULL
); -- Account balance is ignored in this database system

CREATE TABLE TRANSACTIONS (
    T_NUM       INTEGER     PRIMARY KEY,
    T_TIME      INTEGER     NOT NULL,
    T_FROM      INTEGER     NOT NULL,
    T_TO        INTEGER     NOT NULL,
    T_AMOUNT    FLOAT(15,2) NOT NULL,
    CONSTRAINT  TRANSACTIONS_T_FROM_FK  FOREIGN KEY (T_FROM)    REFERENCES  ACCOUNTS    (A_NUM),
    CONSTRAINT  TRANSACTIONS_T_TO_FK    FOREIGN KEY (T_TO)      REFERENCES  ACCOUNTS    (A_NUM)
);